# Generated by Django 5.0.4 on 2024-04-24 02:06

import django.core.validators
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(db_comment='Количество продукта', help_text='Количество продукта', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество продукта')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'db_table_comment': 'Корзина',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='Название', help_text='Название', max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(db_comment='Slug-имя', help_text='Slug-имя', unique=True, verbose_name='Slug-имя')),
                ('image', django_resized.forms.ResizedImageField(crop=None, db_comment='Изображение', force_format='PNG', help_text='Изображение', keep_meta=True, quality=-1, scale=None, size=(600, 600), upload_to='images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table_comment': 'Категории',
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='Название', help_text='Название', max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(db_comment='Slug-имя', help_text='Slug-имя', unique=True, verbose_name='Slug-имя')),
                ('image', django_resized.forms.ResizedImageField(crop=None, db_comment='Изображение', force_format='PNG', help_text='Изображение', keep_meta=True, quality=-1, scale=None, size=(600, 600), upload_to='images/', verbose_name='Изображение')),
                ('medium_image', django_resized.forms.ResizedImageField(crop=None, db_comment='Среднее изображение', force_format='PNG', help_text='Среднее изображение', keep_meta=True, quality=-1, scale=None, size=(300, 300), upload_to='images/', verbose_name='Среднее изображение')),
                ('little_image', django_resized.forms.ResizedImageField(crop=None, db_comment='Маленькое изображение', force_format='PNG', help_text='Маленькое изображение', keep_meta=True, quality=-1, scale=None, size=(100, 100), upload_to='images/', verbose_name='Маленькое изображение')),
                ('price', models.PositiveIntegerField(db_comment='Цена продукта', help_text='Цена', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table_comment': 'Продукт',
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='Название', help_text='Название', max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(db_comment='Slug-имя', help_text='Slug-имя', unique=True, verbose_name='Slug-имя')),
                ('image', django_resized.forms.ResizedImageField(crop=None, db_comment='Изображение', force_format='PNG', help_text='Изображение', keep_meta=True, quality=-1, scale=None, size=(600, 600), upload_to='images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'db_table_comment': 'Подкатегория',
                'ordering': ('title',),
                'abstract': False,
            },
        ),
    ]
