# Generated by Django 5.0.4 on 2024-04-24 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(db_comment='Пользователь', help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='basket_products', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(db_comment='Продукт', help_text='Продукт', on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='products.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(db_comment='Категория', help_text='Категория', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(db_comment='Подкатегория продукта', help_text='Подкатегория продукта', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.subcategory', verbose_name='Подкатегория продукта'),
        ),
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together={('user', 'product')},
        ),
    ]
